### ISSUE TITLE
Wrong # of arguments

### ISSUE THREAD

**Issue by kswirydo** [haldaas/Nystrom--Schur-Preconditioner#2]
I am trying to reproduce the results from the paper.  I downloaded the code, dowloaded Metis 4, compiled the mex file and I am getting
`Error using metismex
Wrong # of arguments

Error in OneLevelKwayNestedDissection (line 13)
[perm, ~,sizes] = metismex('NodeNDP', A, nbPartition);

Error in main (line 45)
[permutation,partsize,partbegin,partend] = OneLevelKwayNestedDissection(AP, level);`

I am just not sure what am I doing wrong.
Thank you!

**Comment by haldaas** [comment]
Please compile the metismex.c now available in the repo. It has the correct interface.

**Comment by kswirydo** [comment]
Now it works okay. Thank you!!!
